### ISSUE TITLE
About BackoffDelay

### ISSUE THREAD

**Issue by ArtanisCV** [avast/retry-go#17]
I am confused about this part in BackoffDelay https://github.com/avast/retry-go/blob/master/options.go#L62 .

As `n` is starting from 0, why there is a `-1` when computing the delay? Shouldn't it be `config.delay * (1 << n)`?

Thanks in advance.

**Comment by sjanota** [comment]
You're right. It looks like the first retry is executed immediately. I'm not sure if it is on purpose or not.

**Comment by sjanota** [comment]
I have created a PR with a fix (#19) in the case it is a bug.
