### ISSUE TITLE
Enhancement: make error message customizable

### ISSUE THREAD

**Issue by andig** [avast/retry-go#29]
`All attempts fail` doesn't seem entirely go-ish: errors should (?) be lower case and read `failed` instead of `fail`.

Happy to do a quick PR if that helps.

**Comment by JaSei** [comment]
Hi, @andig, thanks for your comment. I will be happy when you send me PR.
Please can you send me too best practice for the go-ish error? Thanks

**Comment by andig** [comment]
@JaSei it would be great to

- fix the translation
- return error message in go style
- return all errors individually similar to https://github.com/go-playground/validator/blob/master/errors.go#L37

If you'd accept a PR I'd be happy to provide one.

**Comment by andig** [comment]
Excuse me. I'm closing this one- seems the wrapped errors are already available. All that would need to be fixed is imho 

    all attempts failed

as error message
