### ISSUE TITLE
WaitAndRetry

### ISSUE THREAD

**Issue by Jurabek** [avast/retry-go#32]
Super useful library,
I could not find a way to use wait and retry, I tried CombineDelay but no success.
is it possible to achieve similar functionality using retry-go?
```
Policy
  .Handle<SomeExceptionType>()
  .WaitAndRetry(new[]
  {
    TimeSpan.FromSeconds(1),
    TimeSpan.FromSeconds(2),
    TimeSpan.FromSeconds(3)
  }, (exception, timeSpan) => {
    // Add logic to be executed before each retry, such as logging    
  });
```
This means, you can configure delays after each attempt, first wait 1 second, then 2 second and etc...

**Comment by JaSei** [comment]
Hi @Jurabek the idea of your snippet is first to try delay is 1s, second 2s, third 3s, and next one 3s too? I think this is possible to do by custom DelayFunction. I maybe add some examples of how to make custom DelayFunctions to README or examples.

**Comment by JaSei** [comment]
Great I have it in examples
https://github.com/avast/retry-go/blob/master/examples/custom_retry_function_test.go

in your case can be easily solved by something like:
```
retry.DelayType(func(n uint, config *retry.Config) time.Duration {
                        switch n {
                        case 1:
                            return 1
                        case 2:
                            return 2
                        default:
                            return 3
                        }
		}),
```

**Comment by Jurabek** [comment]
Hi @JaSei, yes this one was exactly what I need, thank you for the example.
