### ISSUE TITLE
Feedback: nice, but missing context and delay based on error

### ISSUE THREAD

**Issue by sranka** [avast/retry-go#33]
I like the way of the retry strategy design that allows easy composition out of the built-in primitives. I cannot, however, use this library for two reasons:
1. It does not accept a standard go context, the retriable operation has to wait even though the surrounding context might be already canceled.
2. It does not allow me to compute the next retry delay out of the operation error itself. I use a cloud database (InfluxDB) that is accessible over HTTP and my app is a client to the database. [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) is a standard mechanism that HTTP servers use to signalize to the clients the next possible time for the operation to be retried. I can't use it

As a solution with this library, I could possibly use a retry strategy from this library and combine it with another implementation from [your links](https://github.com/avast/retry-go#see-also) that supports go context.

**Comment by JaSei** [comment]
Hi, @sranka I like the context idea. I create PR for this soon.
I think the second thing is possible to do by own DelayFunction

**Comment by sranka** [comment]
Thank you for such a swift response. I did not find a (clean) way for the second UC, because the delay function currently does not accept err, but an "attempt" number and config :

https://github.com/avast/retry-go/blob/01ec76535c8c95d94e71411136a304100b43f596/retry.go#L130

**Comment by JaSei** [comment]
Ok, that's a good point. I will be thinking about - is sounds like send `error` to DelayFunction should solve this trouble :thinking:

**Comment by JaSei** [comment]
@sranka can you please look at :point_up: PR? thanks

the second problem I'll make PR soon...

btw. I add to `SEE ALSO` section https://github.com/sethvargo/go-retry module - maybe is more helpful for you? or if we implement those two things, is this module enough?

thanks

**Comment by sranka** [comment]
Yes, the two requested changes would be enough for me to start using this library, the timing however matters more to me now. I could possibly go with https://github.com/matryer/try, but I am now going with a simple implementation on my own. I just wanted to let you know by posting an issue.

**Comment by JaSei** [comment]
Please look at #35 - delay based on error
thanks

**Comment by JaSei** [comment]
version 3.0.0 was released
