### ISSUE TITLE
Provide a sensible way to retry indefinitely

### ISSUE THREAD

**Issue by edigaryev** [avast/retry-go#43]
Imagine a Go server that is dependent on some bootstrap data and there's little sense in continuing the execution unless that data is retrieved.

With all the perks this package gives (precise delay control, exponential backoff, context support) it would be nice to use it for this case, however, it's currently not possible to do this cleanly:

* specifying `retry.Attempts(0)` does not work as one might expect: https://github.com/avast/retry-go/issues/41
* specifying `retry.Attempts(arbitrarily large number)` is not semantically sound as we don't know the exact number of attempts in advance
* specifying `retry.Attempts(math.MaxUint32)` is a bad idea due to: https://github.com/avast/retry-go/blob/1065640017543f39e8b4885accc7ef52ba22d28c/retry.go#L120

It would be nice if `retry.Attempts(0)` could be used for this case, as `retry.Attempts(0)` is kinda useless in the current implementation: it always results in `All attempts fail: ...` error.

**Comment by JaSei** [comment]
Hi, @edigaryev. I take the point. I feel `Attempts(0)` could be like infinite attempts, probably it's more logical than current behavior #41.
I will look at it, or PR is welcome.

**Comment by JaSei** [comment]
v4 released #49
