### ISSUE TITLE
how to custom, for example, [5s, 30s,5min]

### ISSUE THREAD

**Issue by lihongyan03** [avast/retry-go#52]
how to custom, for example, [5s, 30s,5min]

**Comment by JaSei** [comment]
Hi @lihongyan03 
what about something like this?

```
retry.DelayType(func(n uint, err error, config *retry.Config) time.Duration {
    predefined = []time.Duration{5*time.Second, 30*time.Second, 5*time.Minute}
    if n>len(predefined) {
        return predefined[len(predefined)-1]
    }
    return predefined[n]
}),
```

**Comment by lihongyan03** [comment]
> Hi @lihongyan03 what about something like this?
> 
> ```
> retry.DelayType(func(n uint, err error, config *retry.Config) time.Duration {
>     predefined = []time.Duration{5*time.Second, 30*time.Second, 5*time.Minute}
>     if n>len(predefined) {
>         return predefined[len(predefined)-1]
>     }
>     return predefined[n]
> }),
> ```

**Comment by lihongyan03** [comment]
thanks, it works, @JaSei 
but because of the particularity of the business，I need to turn off the first retry without interval
just like the first retry interval：3s，the second retry interval：30s
instead of the first retry interval：0s，the second retry interval：3s，the third retry interva：30s
How to achieve it ?

**Comment by JaSei** [comment]
what about `predefined = []time.Duration{0*time.Second, 5*time.Second, 30*time.Second, 5*time.Minute}`?

**Comment by lihongyan03** [comment]
I think i know how to do it
thanks very much
