### ISSUE TITLE
Not calling RetryIfFunc when Attempt(0)

### ISSUE THREAD

**Issue by ruijunwang** [avast/retry-go#66]
From https://github.com/c1moore/retry-go/blob/063f78a88594e87168af0d800eac16839b533bcb/retry.go#L99, looks like the retryIf func is not called at all when attempt is set to 0, and I saw the same thing in my code. Is this intended or does it need to be fixed?

**Comment by simonhoss** [comment]
I have the same behavior and would expect that it retries as long as the `RetryIf` returns true

**Comment by merusso** [comment]
I wonder if this causes #83
