### ISSUE TITLE
Proposal: pluggable backoff strategies

### ISSUE THREAD

**Issue by codyaray** [avast/retry-go#9]
Exponential backoff is frequently useful, but sometimes you just want a fixed delay or a delay +/- some random jitter. Seems like you could just take an extra option like `retry.Strategy(retry.Exponential)` or `retry.Jitter` or `retry.Constant` or something.

**Comment by JaSei** [comment]
Good idea, I look at it...

**Comment by JaSei** [comment]
done by #12
